version: '3.3'


services:
  pshp-api:
      container_name: api
      build: ./pshp-api
      ports:
          - 8000:8000
      depends_on:
          - db
      environment:
          DB_NAMESPACE: prushoppe
          DB_SCHEMA: prushoppe-bucket
          DB_HOSTNAME: couchbase://db:8091
          DB_USERNAME: Administrator
          DB_PASSWORD: password
          # DB_USERNAME_FILE: ./secrets/DB_USERNAME
          # DB_PASSWORD_FILE: ./secrets/DB_PASSWORD
          ENCRYPTION_KEY: SmFOY1JmVWpYbjJyNXU4eC9BP0QoRytLYlBlU2dWa1k
          # ENCRYPTION_KEY_FILE: ./secrets/ENCRYPTION_KEY
          ENCRYPTION_ALGORITHM: aes-256-cbc
          ENCRYPTION_IV_LENGTH: 16  
          # API_ACCESS_KEY_FILE: ./secrets/API_ACCESS_KEY
          # ROOT_USER_PASS_FILE: ./secrets/ROOT_USER_PASS
          API_ACCESS_KEY: api-test-pass
          ROOT_USER_PASS: api-test-pass
          APP_NAME: prushoppe
          SCHEMA_URL: http://localhost:8000/prushoppe/api/schema
          SERVICE_URL: http://localhost:8000/prushoppe/api/schema/prushoppe/api
          SERVICE_NAMESPACE: prushoppe
          SERVICE_PORT: 8000
          WORKFLOW_BUCKET: workflow-data
          WORKFLOW_START_URL: http://ps-workflow-svc.phlife-dev-az1-pluk-workflow-engine:12009/process/start
          PRUONE_GET_TASK_WORKFLOW_URL: http://ps-workflow-svc.phlife-dev-az1-pluk-workflow-engine:12009/query/all/variables/searchTask
          PRUSHOPPE_BUCKET: prushoppe-bucket
          API_PAYMENT_ENDPOINT : https://pruone-payment
          API_PAYMENT_LINK_URL : prushoppe/payment
          API_PAYMENT_STATUS_URL : prushoppe/status
          FISERV_API_URL: https://pruaml1-preprd.pru.intranet.asia/FCRMWrapper/FCRMWrapper.asmx?op=RealtimeWLFScreening
          FISERV_HOST: pruaml1-preprd.pru.intranet.asia
          FISERV_AUTH_USERNAME: fcrmrtsuser2
          FISERV_AUTH_PASSWORD: Today12345
          FISERV_APPID: PRULifeYourTerm
          FCRM_PRODUCT_ID: "PLUK#X5499"
          RTS_ALERT_RECIPIENT: phi.aml@prulifeuk.com.ph 
          RTS_ALERT_SENDER: prushoppe@prulifeuk.com.ph  
          API_EMAIL_ENDPOINT: http://svc-notif:12006/notification/sendEmailWithAttachment
          API_PRISM_ENDPOINT: http://pgl-psgr-svc:8004/postgre/getAgentInfo
          KAFKA_PRODUCE_URL: http://ps-kafka-svc.phlife-dev-az1-pluk-workflow-common:9096/produce
          API_GENERATEDOC_ENDPOINT: http://ps-doc-gen-svc:3100/api/generateDoc
          API_PRUSHOPPE_PRODUCT_CODE: PYT
          API_PAYMENT_APPLICATION_NAME: PRUSHOPPE
          API_PAYMENT_LINK_ENDPOINT: http://pyt-core-svc:10001/generatePaymentUrl
          API_PAYMENT_STATUS_ENDPOINT: http://pyt-core-svc:10001/firstdata/inquiryOrder
          API_PAYMENT_PROVIDER: FIRSTDATA
          # BASE_API_URL: http://localhost:8000/
          BASE_API_URL: https://prushoppe-api-uat.prulifeuk.com.ph
          BASE_WEB_URL: https://prushoppe-uat.prulifeuk.com.ph
          DEFAULT_AGENT_CODE: 70010967
          DEFAULT_AGENT_NAME: KQYGMXTOWMFQMJMIOWPYLRL DRNNCT
          DEFAULT_AGENT_FIRSTNAME: KQYGMXTOWMFQMJMIOWPYLRL
          DEFAULT_AGENT_LASTNAME: DRNNCT
          # DEFAULT_AGENT_CODE: 70082582
          # DEFAULT_AGENT_NAME: "HEAD OFFICE AGENT"
          # DEFAULT_AGENT_FIRSTNAME: "HEAD OFFICE"
          # DEFAULT_AGENT_LASTNAME: AGENT
          ALLOWED_DOMAINS: http://localhost:8000,http://127.0.0.1:8000,http://localhost:5500,http://127.0.0.1:5500,https://prushoppe-uat.prulifeuk.com.ph, https://chats.landbot.io, ,https://chats.landbot.pro, https://landbot.io,https://landbot.pro, https://cdn.landbot.io,https://prushoppe-api-uat.prulifeuk.com.ph,https://ps-core-svc-phlife-dev-az1-pluk-capability.aks-lb1-phlife-uat-az1-ntibul.pru.intranet.asia
          ALLOWED_REFERERS: http://localhost:8000,http://127.0.0.1:8000,http://localhost:5500,http://127.0.0.1:5500,https://ps-core-svc-phlife-dev-az1-pluk-capability.aks-lb1-phlife-uat-az1-ntibul.pru.intranet.asia/prushoppe/api-docs/,https://ps-core-svc-phlife-dev-az1-pluk-capability.aks-lb1-phlife-uat-az1-ntibul.pru.intranet.asia/prushoppe-api/schema/
          NEXTDAY_CRON_INTERVAL: '0 */10 * * * *'
          NON_OIR_CRON_INTERVAL: '0 */1 * * * *'
          NON_OIR_CRON_FROM_MINUTES: 3
          NON_OIR_CRON_TO_MINUTES: 90
          API_CHECK_PAYMENT_STATUS_ENDPOINT: http://ps-core-svc:8000/api/payment/status
          
          CUSTOMER_CREATE_RATE_LIMIT_MS: 10000
          CUSTOMER_CREATE_RATE_LIMIT_MAX: 1
          CUSTOMER_UPDATE_RATE_LIMIT_MS: 2000
          CUSTOMER_UPDATE_RATE_LIMIT_MAX: 1
          DOCS_RATE_LIMIT_MS: 3000
          DOCS_RATE_LIMIT_MAX: 10
          PREMIUM_RATE_LIMIT_MS: 10000
          PREMIUM_RATE_LIMIT_MAX: 1
          PAYMENT_LINK_RATE_LIMIT_MS: 5000
          PAYMENT_LINK_RATE_LIMIT_MAX: 1
          PAYMENT_STATUS_RATE_LIMIT_MS: 5000
          PAYMENT_STATUS_RATE_LIMIT_MAX: 1
          
          ENABLE_POSTMAN_TOKEN: postman-token
          ENABLE_CRON_JOBS: 'No'
  db:
    container_name: db
    image: couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - C:\Users\servicio\Documents\temp\couch-data:/opt/couchbase/var/

